export const ITEM_ADDED = 'ITEM_ADDED';
export const ITEM_SAVED = 'ITEM_SAVED';
export const ITEM_DELETED = 'ITEM_DELETED';
export const START_EDITING_ITEM = 'START_EDITING_ITEM';
export const STOP_EDITING_ITEM = 'STOP_EDITING_ITEM';
export const UPDATE_ITEM_TEXT = 'UPDATE_ITEM_TEXT';


export const REQUEST_ITEMS = 'REQUEST_ITEMS';
export const RECEIVE_ITEMS = 'RECEIVE_ITEMS';

export const  FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const  FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE ';
export const  FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';

export const RECEIVE_ITEM = 'RECEIVE_ITEM';
