export const ITEM_SAVED = 'ITEM_SAVED';
export const ITEM_DELETED = 'ITEM_DELETED';
export const START_EDITING_ITEM = 'START_EDITING_ITEM';
export const STOP_EDITING_ITEM = 'STOP_EDITING_ITEM';
export const UPDATE_ITEM_TEXT = 'UPDATE_ITEM_TEXT';

export const FETCH_ITEMS_REQUEST = 'FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_FAILURE = 'FETCH_ITEMS_FAILURE ';
export const FETCH_ITEMS_SUCCESS = 'FETCH_ITEMS_SUCCESS';

export const POST_ITEM_REQUEST = 'POST_ITEM_REQUEST';
export const POST_ITEM_SUCCESS = 'POST_ITEM_SUCCESS';
export const POST_ITEM_FAILURE = 'POST_ITEM_FAILURE';

export const REMOVE_ERROR_MESSAGE = 'REMOVE_ERROR_MESSAGE';
